"use client";
import Link from "next/link";
import React from "react";
import Image from "next/image";
// export const metadata = {
//   title: "Student | Homepage",
//   description: "Generated by create next app",
// };

const page = () => {
  return (
    <div className="container mt-5">
      <h2 className="fw-bold mt-5 text-center">
        Weclocme to <strong className="text-primary">Internshala 🤚</strong>
      </h2>
      <p className="fs-5 text-center">Let’s help you land your dream career</p>
      <div className="py-5">
        <h3 className="fw-bolder text-center mt-2">
          Trending on Internshala 🔥
        </h3>

        <div className="row">
          <div className="col-4 rounded-4" style={{ overflow: "hidden" }}>
            <Image
              src={
                "https://d3atms9ic4lahi.cloudfront.net/banner-images/home_new/pgc_banner-student.png.webp"
              }
              style={{ objectFit: "cover" }}
              width={350}
              height={250}
            />
          </div>
        </div>
      </div>
      {/* <Link className="btn btn-primary me-4" href="/student/signup">
        Signup
      </Link>
     
      <button  className="btn btn-danger"
        data-bs-toggle="modal"
        data-bs-target="#exampleModal">signin</button> */}
    </div>
  );
};

export default page;
