"use client"
import Link from "next/link";
import React from "react";
// export const metadata = {
//   title: "Student | Homepage",
//   description: "Generated by create next app",
// };

const page = () => {
  return (


//     <>
// <div className="container">
// <div className="row">
//   <div className="col-md-8 p-5">
// <h1>Hire interns & freshers
// <i className="text-primary">faster</i>
// </h1>
// <p>Post jobs for free now</p>
// <div>
//   <img src={employeImg} alt="" />
// </div>
//   </div>
//   <div className="col-md-4"></div>
// </div>
// </div>
//     </>
    <div className="container mt-5">
      <Link className="btn btn-primary me-4" href="/student/signup">
        Signup
      </Link>
     
      <button  className="btn btn-danger"
        data-bs-toggle="modal"
        data-bs-target="#exampleModal">signin</button>
    </div>
  );
};

export default page;
