"use client";
import Link from "next/link";
import React, { useState } from "react";
import employeImg from "@/public/employemg.png";
import { useDispatch } from "react-redux";
import { asyncSignupemploye } from "@/store/Actions/employeAction";
import Image from "next/image";
// export const metadata = {
//   title: "Employe | Homepage",
//   description: "Generated by create next app",
// };

const page = () => {
  const dispatch = useDispatch();

  const [formdata, setFormdata] = useState({});
  const [signData, setsignData] = useState({});

  const  onchangeHandler = (e) => {
    setFormdata({ ...formdata, [e.target.name]: e.target.value });
    console.log(formdata);
  };

  const signupHandler = (event) => {
    event.preventDefault();
    dispatch(asyncSignupemploye(formdata));
  };

  return (
    <>
      <div className="container">
        <div className="row">
          <div className="col-md-8 p-5">
            <h1 className="fw-bold" style={{ fontSize: "3.5vw" }}>
              Hire interns & freshers
              <i className="text-primary mx-2 fw-bolder">faster</i>
            </h1>
            <p className="m-1 fs-4  ">
              Post jobs for <strong>free </strong>now
            </p>

            <div>
              <Image   src={employeImg} alt="banner" width={860} height={500} objectFit="cover"/>
              {/* <img src={employeImg} alt=""  /> */}
            </div>
          </div>
          <div className="col-md-4 p-2">
            <div className=" ">
              <div className="">
                {/* <h1>Sign-up and apply for free</h1>
                  <img
                    style={{ marginLeft: "220px" }}
                    src="https://internshala.com/static/images/registration/student_new/underline_d.svg"
                    alt=""
                  />
                </div>

                <p className="fs-4 fw-bolder">
                  1,50,000+ companies hiring on Internshala
                </p> */}
                <div className="shadow p-3  mt-3 bg-body-tertiary rounded">
                  <form onSubmit={signupHandler}>
                    <div className="row mb-3">
                      <div className="mb-3">
                        <label
                          htmlFor="exampleFormControlInput1"
                          className="form-label"
                        >
                          Email address{" "}
                          <span className="text-danger fw-bold">*</span>
                        </label>
                        <input
                          name="email"
                          onChange={onchangeHandler}
                          value={formdata.email}
                          type="email"
                          className="form-control"
                          id="exampleFormControlInput1"
                          placeholder="name@example.com"
                        />
                      </div>
                      <div className="mb-2">
                        <label
                          htmlFor="exampleFormControlInput2"
                          className="form-label"
                        >
                          Enter Password
                          <span className="text-danger fw-bold">*</span>
                        </label>
                        <input
                          name="password"
                          onChange={onchangeHandler}
                          value={formdata.password}
                          type="password"
                          className="form-control"
                          id="exampleFormControlInput2"
                          placeholder="password"
                        />
                      </div>
                    </div>

                    <div className="row mb-2">
                      <div className="col">
                        <label
                          htmlFor="exampleFormControlInput3"
                          className="form-label"
                        >
                          First Name
                          <span className="text-danger fw-bold">*</span>
                        </label>
                        <input
                          onChange={onchangeHandler}
                          value={formdata.firstName}
                          name="firstName"
                          type="text"
                          className="form-control"
                          placeholder="First name"
                          aria-label="First name"
                          id="exampleFormControlInput3"
                        />
                      </div>
                      <div className="col">
                        <label
                          htmlFor="exampleFormControlInput4"
                          className="form-label"
                        >
                          Last Name
                          <span className="text-danger fw-bold">*</span>
                        </label>
                        <input
                          name="lastName"
                          onChange={onchangeHandler}
                          value={formdata.lastName}
                          type="text"
                          className="form-control"
                          placeholder="Last name"
                          aria-label="Last name"
                          id="exampleFormControlInput4"
                        />
                      </div>
                    </div>
                    <div className="row mb-3">
                      <div className="mb-3">
                        <label
                          htmlFor="exampleFormControlInput1"
                          className="form-label"
                        >
                        Company Name
                          <span className="text-danger fw-bold">*</span>
                        </label>
                        <input
                          name="organizationname"
                          onChange={onchangeHandler}
                          value={formdata.organizationname}
                          type="text"
                          className="form-control"
                          id="exampleFormControlInput1"
                          placeholder="Enter Organization Name"
                        />
                      </div>
                      <div className="mb-2">
                        <label
                          htmlFor="exampleFormControlInput2"
                          className="form-label"
                        >
                         Mobile Number
                          <span className="text-danger fw-bold">*</span>
                        </label>
                        <input
                          name="contact"
                          onChange={onchangeHandler}
                          value={formdata.contact}
                          type="number"
                          className="form-control"
                          id="exampleFormControlInput2"
                          placeholder="Enter 10 digit Number"
                        />
                      </div>
                    </div>
                 
                    <div className="d-grid gap-2 my-5">
                      <p className="m-0">
                        By signing up, you agree to our{" "}
                        <span className="text-primary">
                          Terms and Conditions
                        </span>
                        .
                      </p>
                      <button className="btn btn-primary" type="submit">
                        Signup
                      </button>
                    </div>
                  </form>

                  <p className="text-center fw-bolder">
                    Already Registerd ?
                    {/* <a
                className="text-decoraton-none text-primary mx-2"
                href="/signin"
              >
                Signin
              </a> */}
                    {/* <!-- Button trigger modal --> */}
                    <button
                      type="button"
                      className="btn btn-primary ms-3"
                      data-bs-toggle="modal"
                      data-bs-target="#exampleModal"
                    >
                      Login
                    </button>
                  </p>
                </div>
              </div>
              {/* <!-- Modal --> */}
            </div>
          </div>
        </div>
      </div>
      <div className="container p-5 my-5">
        <h1>Why hire on Internshala?</h1>
        <p className="fw-bolder text-black-50">Post jobs and find your ideal candidate</p>
        <div className="row  border border-1">
          <div className="col-md-3 border-end px-5 py-4">
            <h1 className="text-primary fw-bold">21 Mn+</h1>
            <p>candidates looking for jobs and internships</p>
          </div>
          <div className="col-md-3 border-end px-5 py-4">
            <h1 className="text-primary fw-bold">21 Mn+</h1>
            <p>candidates looking for jobs and internships</p>
          </div>
          <div className="col-md-3 border-end px-5 py-4">
            <h1 className="text-primary fw-bold">21 Mn+</h1>
            <p>candidates looking for jobs and internships</p>
          </div>
          <div className="col-md-3 border-end px-5 py-4">
            <h1 className="text-primary fw-bold">21 Mn+</h1>
            <p>candidates looking for jobs and internships</p>
          </div>
        </div>
      </div>
      <div className="container py-5">
<h2 className="fw-bold">A one stop solution for fast & hassle-free hiring</h2>
      </div>
    </>
  );
};

export default page;
